name: Step 1, Enable secret scanning

on: [push]

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check that all required env variables are set
      run: |
        if [ -z "$TO_STEP" ]; then
          echo "TO_STEP is unset or set to the empty string"
          exit 1
        fi
        if [ -z "$FROM_STEP" ]; then
          echo "FROM_STEP is unset or set to the empty string"
          exit 1
        fi
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "GITHUB_TOKEN is unset or set to the empty string"
          exit 1
        fi

    - name: Pull latest changes
      run: |
        git pull origin main

    - name: Check that we are on FROM_STEP
      run: |
        if [ "$(cat .github/steps/-step.txt)" != "$FROM_STEP" ]; then
          echo "Current step is not $FROM_STEP"
          exit 0
        fi

    - name: Update to TO_STEP
      run: |
        echo "$TO_STEP" > .github/steps/-step.txt
        git add .github/steps/-step.txt
        git commit -m "Update to $TO_STEP in STEP and README.md"

    - name: Push changes
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
